version: '3'

networks:
    laravel_news:
    
services:
    nginx:
        image: nginx:alpine
        container_name: laravel_news_nginx
        tty: true
        restart: unless-stopped
        ports:
            - "80:80"
        volumes: 
            - ./src:/var/www/html/:cached
            - ./nginx/nginxconfig.io-localhost/nginx.conf:/etc/nginx/nginx.conf:cached
            - ./nginx/nginxconfig.io-localhost/nginxconfig.io:/etc/nginx/nginxconfig.io:cached
            - ./nginx/nginxconfig.io-localhost/default.conf:/etc/nginx/conf.d/default.conf:cached
        depends_on:
            - php
        networks:
            - laravel_news
    
    php:
        build:
            context: .
            dockerfile: Dockerfile
        # image: openbridge/ob_php-fpm
        container_name: laravel_news_php
        working_dir: /var/www/html
        volumes: 
            - ./src:/var/www/html
        ports: 
            - "9000:9000"
        networks:
            - laravel_news
    
    composer:
        image: composer:latest
        container_name: laravel_news_composer
        # command: ["composer", "install"]
        volumes: 
            - ./src:/var/www/html
        working_dir: /var/www/html
        depends_on: 
            - php
        networks: 
            - laravel_news
            
    npm:
        image: node:lts-alpine
        container_name: laravel_news_npm
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel_news
    
    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_news_artisan
        volumes:
            - ./src:/var/www/html
        depends_on:
            - php
        working_dir: /var/www/html
        entrypoint: ['php', '/var/www/html/artisan']
        networks:
            - laravel_news
    
    redis:
        image: redis:alpine
        container_name: laravel_news_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel_news